{{- if .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veyron.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "veyron.labels" . | nindent 4 }}
type: Opaque
stringData:
  license.key: {{ .Values.license.key | quote }}
{{- end }}
