import type { CSSProperties } from "react";
import { errorBox } from "./ErrorBanner";
import { capabilityBox } from "./CapabilityBanner";

export const panelStyles: Record<string, CSSProperties> = {
  wrap: { marginTop: 12, borderTop: "1px solid #eee", paddingTop: 12 },
  toggle: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    padding: 0,
    color: "#222",
  },
  panel: { marginTop: 10, fontSize: 13, color: "#333" },
  row: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "flex-end", marginTop: 10 },
  label: { display: "flex", flexDirection: "column", gap: 4, fontSize: 12 },
  input: { width: 100, padding: 6, border: "1px solid #ddd", borderRadius: 4 },
  inputWide: { minWidth: 180, padding: 6, border: "1px solid #ddd", borderRadius: 4 },
  btnPrimary: {
    padding: "8px 12px",
    background: "#f0583a",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
  },
  btnDanger: {
    padding: "8px 12px",
    background: "#f44336",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
  },
  btnSuccess: {
    padding: "8px 12px",
    background: "rgba(34,197,94,.15)",
    color: "#15803d",
    border: "1px solid rgba(34,197,94,.35)",
    borderRadius: 4,
    cursor: "pointer",
  },
  btnWarn: {
    padding: "8px 12px",
    background: "rgba(244,63,94,.12)",
    color: "#be123c",
    border: "1px solid rgba(244,63,94,.28)",
    borderRadius: 4,
    cursor: "pointer",
  },
  muted: { color: "#888", margin: "4px 0" },
  note: { color: "#666", fontSize: 12, margin: "4px 0" },
  mono: { fontFamily: "monospace", fontSize: 12, wordBreak: "break-all" },
  hint: { fontSize: 12, color: "#666", marginTop: 8 },
  err: { color: "#c62828", margin: "4px 0" },
  ok: { color: "#15803d", margin: "4px 0" },
  errorBox,
  capabilityBox,
};
