//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VeyronVM) DeepCopyInto(out *VeyronVM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VeyronVM) DeepCopy() *VeyronVM {
	if in == nil {
		return nil
	}
	out := new(VeyronVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *VeyronVM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VeyronVMList) DeepCopyInto(out *VeyronVMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeyronVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VeyronVMList) DeepCopy() *VeyronVMList {
	if in == nil {
		return nil
	}
	out := new(VeyronVMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *VeyronVMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VeyronVMSpec) DeepCopyInto(out *VeyronVMSpec) {
	*out = *in
	out.CPU = in.CPU
	if in.CPU.Model != nil {
		in, out := &in.CPU.Model, &out.CPU.Model
		*out = new(string)
		**out = **in
	}
	if in.CPU.DedicatedCPUPlacement != nil {
		in, out := &in.CPU.DedicatedCPUPlacement, &out.CPU.DedicatedCPUPlacement
		*out = new(bool)
		**out = **in
	}
	if in.CPU.IsolateEmulatorThread != nil {
		in, out := &in.CPU.IsolateEmulatorThread, &out.CPU.IsolateEmulatorThread
		*out = new(bool)
		**out = **in
	}
	out.Memory = in.Memory
	if in.Memory.HugepagesPageSize != nil {
		in, out := &in.Memory.HugepagesPageSize, &out.Memory.HugepagesPageSize
		*out = new(string)
		**out = **in
	}
	if in.Memory.MaxGuest != nil {
		in, out := &in.Memory.MaxGuest, &out.Memory.MaxGuest
		*out = new(string)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(CloudInitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(FirmwareSpec)
		**out = **in
	}
	if in.Clock != nil {
		in, out := &in.Clock, &out.Clock
		*out = new(ClockSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionStrategy != nil {
		in, out := &in.EvictionStrategy, &out.EvictionStrategy
		*out = new(string)
		**out = **in
	}
	if in.TerminationGracePeriod != nil {
		in, out := &in.TerminationGracePeriod, &out.TerminationGracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.AllowInternet != nil {
		in, out := &in.AllowInternet, &out.AllowInternet
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VeyronVMSpec) DeepCopy() *VeyronVMSpec {
	if in == nil {
		return nil
	}
	out := new(VeyronVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VeyronVMStatus) DeepCopyInto(out *VeyronVMStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VeyronVMStatus) DeepCopy() *VeyronVMStatus {
	if in == nil {
		return nil
	}
	out := new(VeyronVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DiskSpec) DeepCopyInto(out *DiskSpec) {
	*out = *in
	out.Source = in.Source
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.Bus != nil {
		in, out := &in.Bus, &out.Bus
		*out = new(string)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(string)
		**out = **in
	}
	if in.IO != nil {
		in, out := &in.IO, &out.IO
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DiskSpec) DeepCopy() *DiskSpec {
	if in == nil {
		return nil
	}
	out := new(DiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DiskSource) DeepCopyInto(out *DiskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DiskSource) DeepCopy() *DiskSource {
	if in == nil {
		return nil
	}
	out := new(DiskSource)
	*out = *in
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InterfaceSpec) DeepCopyInto(out *InterfaceSpec) {
	*out = *in
	out.NetworkType = in.NetworkType
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InterfaceSpec) DeepCopy() *InterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CloudInitSpec) DeepCopyInto(out *CloudInitSpec) {
	*out = *in
	if in.NetworkData != nil {
		in, out := &in.NetworkData, &out.NetworkData
		*out = new(string)
		**out = **in
	}
	if in.UserDataSecretRef != nil {
		in, out := &in.UserDataSecretRef, &out.UserDataSecretRef
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CloudInitSpec) DeepCopy() *CloudInitSpec {
	if in == nil {
		return nil
	}
	out := new(CloudInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CPUSpec) DeepCopyInto(out *CPUSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.DedicatedCPUPlacement != nil {
		in, out := &in.DedicatedCPUPlacement, &out.DedicatedCPUPlacement
		*out = new(bool)
		**out = **in
	}
	if in.IsolateEmulatorThread != nil {
		in, out := &in.IsolateEmulatorThread, &out.IsolateEmulatorThread
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CPUSpec) DeepCopy() *CPUSpec {
	if in == nil {
		return nil
	}
	out := new(CPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
	if in.HugepagesPageSize != nil {
		in, out := &in.HugepagesPageSize, &out.HugepagesPageSize
		*out = new(string)
		**out = **in
	}
	if in.MaxGuest != nil {
		in, out := &in.MaxGuest, &out.MaxGuest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *FeaturesSpec) DeepCopyInto(out *FeaturesSpec) {
	*out = *in
	if in.HyperV != nil {
		in, out := &in.HyperV, &out.HyperV
		*out = new(HyperVSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KVMHidden != nil {
		in, out := &in.KVMHidden, &out.KVMHidden
		*out = new(bool)
		**out = **in
	}
	if in.SMM != nil {
		in, out := &in.SMM, &out.SMM
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *FeaturesSpec) DeepCopy() *FeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HyperVSpec) DeepCopyInto(out *HyperVSpec) {
	*out = *in
	if in.Spinlocks != nil {
		in, out := &in.Spinlocks, &out.Spinlocks
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HyperVSpec) DeepCopy() *HyperVSpec {
	if in == nil {
		return nil
	}
	out := new(HyperVSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *FirmwareSpec) DeepCopyInto(out *FirmwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *FirmwareSpec) DeepCopy() *FirmwareSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareSpec)
	*out = *in
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ClockSpec) DeepCopyInto(out *ClockSpec) {
	*out = *in
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Timers != nil {
		in, out := &in.Timers, &out.Timers
		*out = new(TimersSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ClockSpec) DeepCopy() *ClockSpec {
	if in == nil {
		return nil
	}
	out := new(ClockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TimersSpec) DeepCopyInto(out *TimersSpec) {
	*out = *in
	if in.HPETPresent != nil {
		in, out := &in.HPETPresent, &out.HPETPresent
		*out = new(bool)
		**out = **in
	}
	if in.PITTickPolicy != nil {
		in, out := &in.PITTickPolicy, &out.PITTickPolicy
		*out = new(string)
		**out = **in
	}
	if in.RTCTickPolicy != nil {
		in, out := &in.RTCTickPolicy, &out.RTCTickPolicy
		*out = new(string)
		**out = **in
	}
	if in.HyperVPresent != nil {
		in, out := &in.HyperVPresent, &out.HyperVPresent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TimersSpec) DeepCopy() *TimersSpec {
	if in == nil {
		return nil
	}
	out := new(TimersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NetworkType) DeepCopyInto(out *NetworkType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NetworkType) DeepCopy() *NetworkType {
	if in == nil {
		return nil
	}
	out := new(NetworkType)
	*out = *in
	return out
}

// --- VeyronBlueprint ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VeyronBlueprint) DeepCopyInto(out *VeyronBlueprint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VeyronBlueprint) DeepCopy() *VeyronBlueprint {
	if in == nil {
		return nil
	}
	out := new(VeyronBlueprint)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronBlueprint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronBlueprintList) DeepCopyInto(out *VeyronBlueprintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeyronBlueprint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronBlueprintList) DeepCopy() *VeyronBlueprintList {
	if in == nil {
		return nil
	}
	out := new(VeyronBlueprintList)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronBlueprintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronBlueprintSpec) DeepCopyInto(out *VeyronBlueprintSpec) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]BlueprintVMSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *VeyronBlueprintSpec) DeepCopy() *VeyronBlueprintSpec {
	if in == nil {
		return nil
	}
	out := new(VeyronBlueprintSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronBlueprintStatus) DeepCopyInto(out *VeyronBlueprintStatus) {
	*out = *in
	if in.DeploymentOrder != nil {
		in, out := &in.DeploymentOrder, &out.DeploymentOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VMStatuses != nil {
		in, out := &in.VMStatuses, &out.VMStatuses
		*out = make([]VMDeploymentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronBlueprintStatus) DeepCopy() *VeyronBlueprintStatus {
	if in == nil {
		return nil
	}
	out := new(VeyronBlueprintStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BlueprintVMSpec) DeepCopyInto(out *BlueprintVMSpec) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(uint32)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(string)
		**out = **in
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(VeyronVMSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BlueprintVMSpec) DeepCopy() *BlueprintVMSpec {
	if in == nil {
		return nil
	}
	out := new(BlueprintVMSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMDeploymentStatus) DeepCopyInto(out *VMDeploymentStatus) {
	*out = *in
}

func (in *VMDeploymentStatus) DeepCopy() *VMDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(VMDeploymentStatus)
	*out = *in
	return out
}

// --- VeyronPolicy ---

func (in *VeyronPolicy) DeepCopyInto(out *VeyronPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VeyronPolicy) DeepCopy() *VeyronPolicy {
	if in == nil {
		return nil
	}
	out := new(VeyronPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronPolicyList) DeepCopyInto(out *VeyronPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeyronPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronPolicyList) DeepCopy() *VeyronPolicyList {
	if in == nil {
		return nil
	}
	out := new(VeyronPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronPolicySpec) DeepCopyInto(out *VeyronPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRuleSpec, len(*in))
		copy(*out, *in)
	}
}

func (in *VeyronPolicySpec) DeepCopy() *VeyronPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VeyronPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronPolicyStatus) DeepCopyInto(out *VeyronPolicyStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]PolicyViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
}

func (in *VeyronPolicyStatus) DeepCopy() *VeyronPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VeyronPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyRuleSpec) DeepCopyInto(out *PolicyRuleSpec) {
	*out = *in
}

func (in *PolicyRuleSpec) DeepCopy() *PolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleSpec)
	*out = *in
	return out
}

func (in *PolicyViolation) DeepCopyInto(out *PolicyViolation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

func (in *PolicyViolation) DeepCopy() *PolicyViolation {
	if in == nil {
		return nil
	}
	out := new(PolicyViolation)
	in.DeepCopyInto(out)
	return out
}

// --- VeyronInsight ---

func (in *VeyronInsight) DeepCopyInto(out *VeyronInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VeyronInsight) DeepCopy() *VeyronInsight {
	if in == nil {
		return nil
	}
	out := new(VeyronInsight)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronInsightList) DeepCopyInto(out *VeyronInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeyronInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronInsightList) DeepCopy() *VeyronInsightList {
	if in == nil {
		return nil
	}
	out := new(VeyronInsightList)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronInsightSpec) DeepCopyInto(out *VeyronInsightSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]InsightMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronInsightSpec) DeepCopy() *VeyronInsightSpec {
	if in == nil {
		return nil
	}
	out := new(VeyronInsightSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronInsightStatus) DeepCopyInto(out *VeyronInsightStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronInsightStatus) DeepCopy() *VeyronInsightStatus {
	if in == nil {
		return nil
	}
	out := new(VeyronInsightStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *InsightMetric) DeepCopyInto(out *InsightMetric) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

func (in *InsightMetric) DeepCopy() *InsightMetric {
	if in == nil {
		return nil
	}
	out := new(InsightMetric)
	in.DeepCopyInto(out)
	return out
}

// --- VeyronAction ---

func (in *VeyronAction) DeepCopyInto(out *VeyronAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VeyronAction) DeepCopy() *VeyronAction {
	if in == nil {
		return nil
	}
	out := new(VeyronAction)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronActionList) DeepCopyInto(out *VeyronActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeyronAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronActionList) DeepCopy() *VeyronActionList {
	if in == nil {
		return nil
	}
	out := new(VeyronActionList)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VeyronActionSpec) DeepCopyInto(out *VeyronActionSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *VeyronActionSpec) DeepCopy() *VeyronActionSpec {
	if in == nil {
		return nil
	}
	out := new(VeyronActionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VeyronActionStatus) DeepCopyInto(out *VeyronActionStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VeyronActionStatus) DeepCopy() *VeyronActionStatus {
	if in == nil {
		return nil
	}
	out := new(VeyronActionStatus)
	in.DeepCopyInto(out)
	return out
}
