//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VMRogueVM) DeepCopyInto(out *VMRogueVM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VMRogueVM) DeepCopy() *VMRogueVM {
	if in == nil {
		return nil
	}
	out := new(VMRogueVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *VMRogueVM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VMRogueVMList) DeepCopyInto(out *VMRogueVMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRogueVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VMRogueVMList) DeepCopy() *VMRogueVMList {
	if in == nil {
		return nil
	}
	out := new(VMRogueVMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *VMRogueVMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VMRogueVMSpec) DeepCopyInto(out *VMRogueVMSpec) {
	*out = *in
	out.CPU = in.CPU
	if in.CPU.Model != nil {
		in, out := &in.CPU.Model, &out.CPU.Model
		*out = new(string)
		**out = **in
	}
	if in.CPU.DedicatedCPUPlacement != nil {
		in, out := &in.CPU.DedicatedCPUPlacement, &out.CPU.DedicatedCPUPlacement
		*out = new(bool)
		**out = **in
	}
	if in.CPU.IsolateEmulatorThread != nil {
		in, out := &in.CPU.IsolateEmulatorThread, &out.CPU.IsolateEmulatorThread
		*out = new(bool)
		**out = **in
	}
	out.Memory = in.Memory
	if in.Memory.HugepagesPageSize != nil {
		in, out := &in.Memory.HugepagesPageSize, &out.Memory.HugepagesPageSize
		*out = new(string)
		**out = **in
	}
	if in.Memory.MaxGuest != nil {
		in, out := &in.Memory.MaxGuest, &out.Memory.MaxGuest
		*out = new(string)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(CloudInitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(FirmwareSpec)
		**out = **in
	}
	if in.Clock != nil {
		in, out := &in.Clock, &out.Clock
		*out = new(ClockSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionStrategy != nil {
		in, out := &in.EvictionStrategy, &out.EvictionStrategy
		*out = new(string)
		**out = **in
	}
	if in.TerminationGracePeriod != nil {
		in, out := &in.TerminationGracePeriod, &out.TerminationGracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VMRogueVMSpec) DeepCopy() *VMRogueVMSpec {
	if in == nil {
		return nil
	}
	out := new(VMRogueVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VMRogueVMStatus) DeepCopyInto(out *VMRogueVMStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *VMRogueVMStatus) DeepCopy() *VMRogueVMStatus {
	if in == nil {
		return nil
	}
	out := new(VMRogueVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DiskSpec) DeepCopyInto(out *DiskSpec) {
	*out = *in
	out.Source = in.Source
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.Bus != nil {
		in, out := &in.Bus, &out.Bus
		*out = new(string)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(string)
		**out = **in
	}
	if in.IO != nil {
		in, out := &in.IO, &out.IO
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DiskSpec) DeepCopy() *DiskSpec {
	if in == nil {
		return nil
	}
	out := new(DiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DiskSource) DeepCopyInto(out *DiskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DiskSource) DeepCopy() *DiskSource {
	if in == nil {
		return nil
	}
	out := new(DiskSource)
	*out = *in
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InterfaceSpec) DeepCopyInto(out *InterfaceSpec) {
	*out = *in
	out.NetworkType = in.NetworkType
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InterfaceSpec) DeepCopy() *InterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CloudInitSpec) DeepCopyInto(out *CloudInitSpec) {
	*out = *in
	if in.NetworkData != nil {
		in, out := &in.NetworkData, &out.NetworkData
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CloudInitSpec) DeepCopy() *CloudInitSpec {
	if in == nil {
		return nil
	}
	out := new(CloudInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CPUSpec) DeepCopyInto(out *CPUSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.DedicatedCPUPlacement != nil {
		in, out := &in.DedicatedCPUPlacement, &out.DedicatedCPUPlacement
		*out = new(bool)
		**out = **in
	}
	if in.IsolateEmulatorThread != nil {
		in, out := &in.IsolateEmulatorThread, &out.IsolateEmulatorThread
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CPUSpec) DeepCopy() *CPUSpec {
	if in == nil {
		return nil
	}
	out := new(CPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
	if in.HugepagesPageSize != nil {
		in, out := &in.HugepagesPageSize, &out.HugepagesPageSize
		*out = new(string)
		**out = **in
	}
	if in.MaxGuest != nil {
		in, out := &in.MaxGuest, &out.MaxGuest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *FeaturesSpec) DeepCopyInto(out *FeaturesSpec) {
	*out = *in
	if in.HyperV != nil {
		in, out := &in.HyperV, &out.HyperV
		*out = new(HyperVSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KVMHidden != nil {
		in, out := &in.KVMHidden, &out.KVMHidden
		*out = new(bool)
		**out = **in
	}
	if in.SMM != nil {
		in, out := &in.SMM, &out.SMM
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *FeaturesSpec) DeepCopy() *FeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HyperVSpec) DeepCopyInto(out *HyperVSpec) {
	*out = *in
	if in.Spinlocks != nil {
		in, out := &in.Spinlocks, &out.Spinlocks
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HyperVSpec) DeepCopy() *HyperVSpec {
	if in == nil {
		return nil
	}
	out := new(HyperVSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *FirmwareSpec) DeepCopyInto(out *FirmwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *FirmwareSpec) DeepCopy() *FirmwareSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareSpec)
	*out = *in
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ClockSpec) DeepCopyInto(out *ClockSpec) {
	*out = *in
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Timers != nil {
		in, out := &in.Timers, &out.Timers
		*out = new(TimersSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ClockSpec) DeepCopy() *ClockSpec {
	if in == nil {
		return nil
	}
	out := new(ClockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TimersSpec) DeepCopyInto(out *TimersSpec) {
	*out = *in
	if in.HPETPresent != nil {
		in, out := &in.HPETPresent, &out.HPETPresent
		*out = new(bool)
		**out = **in
	}
	if in.PITTickPolicy != nil {
		in, out := &in.PITTickPolicy, &out.PITTickPolicy
		*out = new(string)
		**out = **in
	}
	if in.RTCTickPolicy != nil {
		in, out := &in.RTCTickPolicy, &out.RTCTickPolicy
		*out = new(string)
		**out = **in
	}
	if in.HyperVPresent != nil {
		in, out := &in.HyperVPresent, &out.HyperVPresent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TimersSpec) DeepCopy() *TimersSpec {
	if in == nil {
		return nil
	}
	out := new(TimersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NetworkType) DeepCopyInto(out *NetworkType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NetworkType) DeepCopy() *NetworkType {
	if in == nil {
		return nil
	}
	out := new(NetworkType)
	*out = *in
	return out
}

// --- VMRogueBlueprint ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *VMRogueBlueprint) DeepCopyInto(out *VMRogueBlueprint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VMRogueBlueprint) DeepCopy() *VMRogueBlueprint {
	if in == nil {
		return nil
	}
	out := new(VMRogueBlueprint)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueBlueprint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueBlueprintList) DeepCopyInto(out *VMRogueBlueprintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRogueBlueprint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueBlueprintList) DeepCopy() *VMRogueBlueprintList {
	if in == nil {
		return nil
	}
	out := new(VMRogueBlueprintList)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueBlueprintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueBlueprintSpec) DeepCopyInto(out *VMRogueBlueprintSpec) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]BlueprintVMSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *VMRogueBlueprintSpec) DeepCopy() *VMRogueBlueprintSpec {
	if in == nil {
		return nil
	}
	out := new(VMRogueBlueprintSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueBlueprintStatus) DeepCopyInto(out *VMRogueBlueprintStatus) {
	*out = *in
	if in.DeploymentOrder != nil {
		in, out := &in.DeploymentOrder, &out.DeploymentOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VMStatuses != nil {
		in, out := &in.VMStatuses, &out.VMStatuses
		*out = make([]VMDeploymentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueBlueprintStatus) DeepCopy() *VMRogueBlueprintStatus {
	if in == nil {
		return nil
	}
	out := new(VMRogueBlueprintStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BlueprintVMSpec) DeepCopyInto(out *BlueprintVMSpec) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(uint32)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(string)
		**out = **in
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(VMRogueVMSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BlueprintVMSpec) DeepCopy() *BlueprintVMSpec {
	if in == nil {
		return nil
	}
	out := new(BlueprintVMSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMDeploymentStatus) DeepCopyInto(out *VMDeploymentStatus) {
	*out = *in
}

func (in *VMDeploymentStatus) DeepCopy() *VMDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(VMDeploymentStatus)
	*out = *in
	return out
}

// --- VMRoguePolicy ---

func (in *VMRoguePolicy) DeepCopyInto(out *VMRoguePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VMRoguePolicy) DeepCopy() *VMRoguePolicy {
	if in == nil {
		return nil
	}
	out := new(VMRoguePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRoguePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRoguePolicyList) DeepCopyInto(out *VMRoguePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRoguePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRoguePolicyList) DeepCopy() *VMRoguePolicyList {
	if in == nil {
		return nil
	}
	out := new(VMRoguePolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRoguePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRoguePolicySpec) DeepCopyInto(out *VMRoguePolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRuleSpec, len(*in))
		copy(*out, *in)
	}
}

func (in *VMRoguePolicySpec) DeepCopy() *VMRoguePolicySpec {
	if in == nil {
		return nil
	}
	out := new(VMRoguePolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRoguePolicyStatus) DeepCopyInto(out *VMRoguePolicyStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]PolicyViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
}

func (in *VMRoguePolicyStatus) DeepCopy() *VMRoguePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VMRoguePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyRuleSpec) DeepCopyInto(out *PolicyRuleSpec) {
	*out = *in
}

func (in *PolicyRuleSpec) DeepCopy() *PolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleSpec)
	*out = *in
	return out
}

func (in *PolicyViolation) DeepCopyInto(out *PolicyViolation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

func (in *PolicyViolation) DeepCopy() *PolicyViolation {
	if in == nil {
		return nil
	}
	out := new(PolicyViolation)
	in.DeepCopyInto(out)
	return out
}

// --- VMRogueInsight ---

func (in *VMRogueInsight) DeepCopyInto(out *VMRogueInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VMRogueInsight) DeepCopy() *VMRogueInsight {
	if in == nil {
		return nil
	}
	out := new(VMRogueInsight)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueInsightList) DeepCopyInto(out *VMRogueInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRogueInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueInsightList) DeepCopy() *VMRogueInsightList {
	if in == nil {
		return nil
	}
	out := new(VMRogueInsightList)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueInsightSpec) DeepCopyInto(out *VMRogueInsightSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]InsightMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueInsightSpec) DeepCopy() *VMRogueInsightSpec {
	if in == nil {
		return nil
	}
	out := new(VMRogueInsightSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueInsightStatus) DeepCopyInto(out *VMRogueInsightStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueInsightStatus) DeepCopy() *VMRogueInsightStatus {
	if in == nil {
		return nil
	}
	out := new(VMRogueInsightStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *InsightMetric) DeepCopyInto(out *InsightMetric) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

func (in *InsightMetric) DeepCopy() *InsightMetric {
	if in == nil {
		return nil
	}
	out := new(InsightMetric)
	in.DeepCopyInto(out)
	return out
}

// --- VMRogueAction ---

func (in *VMRogueAction) DeepCopyInto(out *VMRogueAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VMRogueAction) DeepCopy() *VMRogueAction {
	if in == nil {
		return nil
	}
	out := new(VMRogueAction)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueActionList) DeepCopyInto(out *VMRogueActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRogueAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueActionList) DeepCopy() *VMRogueActionList {
	if in == nil {
		return nil
	}
	out := new(VMRogueActionList)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VMRogueActionSpec) DeepCopyInto(out *VMRogueActionSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *VMRogueActionSpec) DeepCopy() *VMRogueActionSpec {
	if in == nil {
		return nil
	}
	out := new(VMRogueActionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VMRogueActionStatus) DeepCopyInto(out *VMRogueActionStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VMRogueActionStatus) DeepCopy() *VMRogueActionStatus {
	if in == nil {
		return nil
	}
	out := new(VMRogueActionStatus)
	in.DeepCopyInto(out)
	return out
}
