apiVersion: v1
kind: ServiceAccount
metadata:
  name: veyron-operator
  namespace: veyron-system
  labels:
    app.kubernetes.io/name: veyron
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veyron-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veyron-operator
subjects:
  - kind: ServiceAccount
    name: veyron-operator
    namespace: veyron-system
