apiVersion: v2
name: veyron-operator
description: Veyron Kubernetes Operator for KubeVirt VM lifecycle (veyron.io CRDs)
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - veyron
  - kubevirt
  - operator
  - virtual-machine
home: https://github.com/hypersdk/Veyron
sources:
  - https://github.com/hypersdk/Veyron
maintainers:
  - name: ZyvorAI Labs Private Limited
    url: https://github.com/hypersdk
