apiVersion: v2
name: veyron
description: Veyron — Kubernetes-native VM command center (KubeVirt)
type: application
version: 0.3.2
appVersion: "0.3.0"
keywords:
  - veyron
  - kubevirt
  - kubernetes
  - virtual-machine
  - kvm
  - vm-management
home: https://github.com/zyvorai/veyron
sources:
  - https://github.com/zyvorai/veyron
maintainers:
  - name: ZyvorAI Labs Private Limited
    url: https://github.com/zyvorai
