apiVersion: vmrogue.io/v1alpha1
kind: VMTemplate
metadata:
  labels:
    vmrogue.io/managed-by: vmrogue-catalog-export
  name: fedora
spec:
  description: 'VMRogue built-in template: fedora'
  tags:
  - linux
  family: linux
  recommendedProfiles:
  - dev
  default:
    cpu:
      cores: 2
      sockets: 1
      threads: 1
    memory:
      size: '4Gi'
    disks:
    - name: rootdisk
      size: '0'
      bootOrder: 1
      source:
        type: containerDisk
        image: quay.io/containerdisks/fedora:latest
      deviceType: disk
    - name: datadisk
      size: '20Gi'
      bootOrder: 2
      source:
        type: blank
      deviceType: disk
    interfaces:
    - name: default
      network: default
      model: virtio
      networkType:
        type: pod
    cloudInit:
      userData: |
        #cloud-config
        user: vmrogue
        password: mn0jKOUnq2j@kMPD
        lock_passwd: false
        chpasswd: { expire: True }
        ssh_pwauth: False
        package_update: true
        packages:
          - qemu-guest-agent
        runcmd:
          - [ systemctl, enable, qemu-guest-agent ]
          - [ systemctl, start, qemu-guest-agent ]
    clock:
      utc: true
      timers:
        hpetPresent: false
        pitTickPolicy: delay
        rtcTickPolicy: catchup
    enableTpm: false
    enableRng: true
    labels:
      os.version: '43'
      os: fedora
    allowInternet: true
