apiVersion: vmrogue.io/v1alpha1
kind: VMTemplate
metadata:
  labels:
    vmrogue.io/managed-by: vmrogue-catalog-export
  name: opensuse-tumbleweed
spec:
  description: 'VMRogue built-in template: opensuse-tumbleweed'
  tags:
  - linux
  family: linux
  recommendedProfiles:
  - dev
  default:
    cpu:
      cores: 2
      sockets: 1
      threads: 1
    memory:
      size: '4Gi'
    disks:
    - name: rootdisk
      size: '20Gi'
      bootOrder: 1
      source:
        type: blank
      deviceType: disk
    interfaces:
    - name: default
      network: default
      model: virtio
      networkType:
        type: pod
    cloudInit:
      userData: "#cloud-config\nuser: vmrogue\npassword: GT#LuR2T8k72WSsw\nlock_passwd: false\nchpasswd: { expire: True }\nssh_pwauth: False\npackage_update: true\npackages:\n  - curl\nwrite_files:\n  - path: /etc/systemd/system/guestkit-agent.service\n    content: |\n      [Unit]\n      Description=GuestKit Agent (Zyvor)\n      After=network.target\n      ConditionPathExists=/dev/virtio-ports/org.qemu.guest_agent.0\n      \n      [Service]\n      ExecStart=/usr/local/bin/guestkit agent --channel virtio\n      Restart=on-failure\n      User=root\n      StandardOutput=journal\n      StandardError=journal\n      \n      [Install]\n      WantedBy=multi-user.target\nruncmd:\n  - [ sh, -c, 'curl -fsSL -o /usr/local/bin/guestkit \"http://vmrogue.vmrogue-system.svc:5151/api/v1/platform/guestkit/binary\"' ]\n  - [ chmod, '0755', /usr/local/bin/guestkit ]\n  - [ systemctl, daemon-reload ]\n  - [ systemctl, enable, guestkit-agent ]\n  - [ systemctl, start, guestkit-agent ]\n"
    clock:
      utc: true
      timers:
        hpetPresent: false
        pitTickPolicy: delay
        rtcTickPolicy: catchup
    enableTpm: false
    enableRng: true
    labels:
      os: opensuse
      os.version: tumbleweed
    allowInternet: true
