apiVersion: vmrogue.io/v1alpha1
kind: VMTemplate
metadata:
  labels:
    vmrogue.io/managed-by: vmrogue-catalog-export
  name: oracle-8
spec:
  description: 'VMRogue built-in template: oracle-8'
  tags:
  - linux
  family: linux
  recommendedProfiles:
  - dev
  default:
    cpu:
      cores: 2
      sockets: 1
      threads: 1
    memory:
      size: '4Gi'
    disks:
    - name: rootdisk
      size: '30Gi'
      bootOrder: 1
      source:
        type: blank
      deviceType: disk
    interfaces:
    - name: default
      network: default
      model: virtio
      networkType:
        type: pod
    cloudInit:
      userData: "#cloud-config\nuser: vmrogue\npassword: 0GAahoLXncbwJze0\nlock_passwd: false\nchpasswd: { expire: True }\nssh_pwauth: False\npackage_update: true\npackages:\n  - curl\nwrite_files:\n  - path: /etc/systemd/system/guestkit-agent.service\n    content: |\n      [Unit]\n      Description=GuestKit Agent (Zyvor)\n      After=network-online.target\n      Wants=network-online.target\n      \n      [Service]\n      ExecStart=/bin/sh -c 'until [ -e /dev/virtio-ports/org.qemu.guest_agent.0 ]; do sleep 2; done; exec /usr/local/bin/guestkit agent --channel virtio'\n      Restart=always\n      RestartSec=5\n      User=root\n      StandardOutput=journal\n      StandardError=journal\n      \n      [Install]\n      WantedBy=multi-user.target\nruncmd:\n  - [ sh, -c, 'for i in $(seq 1 30); do curl -fkSL -o /usr/local/bin/guestkit \"https://vmrogue-api.vmrogue-system.svc/api/v1/platform/guestkit/binary\" && break; sleep 10; done' ]\n  - [ chmod, '0755', /usr/local/bin/guestkit ]\n  - [ systemctl, daemon-reload ]\n  - [ systemctl, enable, guestkit-agent ]\n  - [ systemctl, start, guestkit-agent ]\n"
    clock:
      utc: true
      timers:
        hpetPresent: false
        pitTickPolicy: delay
        rtcTickPolicy: catchup
    enableTpm: false
    enableRng: true
    labels:
      os: oracle
      os.version: '8'
    allowInternet: true
