// Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
// Proprietary software — see LICENSE in the repository root.

//! Trial license enforcement for Veyron.
//!
//! Keys are generated by sales (scripts/gen-trial-key.py) and delivered
//! to trial customers via email. The key encodes the licensee name,
//! issue date, and expiry date, signed with HMAC-SHA256.
//!
//! Key format: <base64url-payload>.<base64url-hmac>
//! Payload JSON: {"p":"veyron","iss":"2026-06-21","exp":"2026-07-21","who":"Acme Corp"}
//!
//! Key lookup order:
//!   1. VEYRON_LICENSE_KEY env var
//!   2. ~/.config/veyron/license.key
//!   3. /etc/veyron/license.key

use anyhow::{bail, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use chrono::{NaiveDate, Utc};
use hmac::{Hmac, Mac};
use sha2::Sha256;
use std::path::PathBuf;

// Embedded HMAC secret — known only to Zyvor Labs.
const HMAC_SECRET: &[u8] = b"zyvor-veyron-trial-v1-9a2f4b8c1d3e6f0a";

type HmacSha256 = Hmac<Sha256>;

#[derive(Debug)]
pub struct License {
    pub licensee: String,
    pub issued: NaiveDate,
    pub expires: NaiveDate,
}

impl License {
    pub fn days_remaining(&self) -> i64 {
        let today = Utc::now().date_naive();
        (self.expires - today).num_days()
    }

    pub fn is_valid(&self) -> bool {
        self.days_remaining() > 0
    }
}

/// Load and validate the license key. Returns `Ok(License)` if valid and not expired.
/// Prints a warning if the license expires within 5 days.
pub fn load_and_check() -> Result<License> {
    let raw = find_key()?;
    let lic = parse_and_verify(&raw)?;
    if !lic.is_valid() {
        bail!(
            "Veyron trial licence expired on {}.\n\
             Contact sales@zyvor.dev to purchase a commercial licence.\n\
             https://zyvor.dev/veyron",
            lic.expires
        );
    }
    let days = lic.days_remaining();
    if days <= 5 {
        eprintln!(
            "⚠  Veyron trial expires in {} day(s) ({}). Contact sales@zyvor.dev to continue.",
            days, lic.expires
        );
    }
    Ok(lic)
}

fn find_key() -> Result<String> {
    if let Ok(k) = std::env::var("VEYRON_LICENSE_KEY") {
        if !k.trim().is_empty() {
            return Ok(k.trim().to_string());
        }
    }
    let candidates = [
        dirs_key_path(),
        PathBuf::from("/etc/veyron/license.key"),
    ];
    for path in &candidates {
        if path.exists() {
            let content = std::fs::read_to_string(path)
                .map_err(|e| anyhow::anyhow!("Cannot read licence key at {}: {}", path.display(), e))?;
            let trimmed = content.trim().to_string();
            if !trimmed.is_empty() {
                return Ok(trimmed);
            }
        }
    }
    bail!(
        "No Veyron licence key found.\n\
         \n\
         Request a 30-day trial at: https://zyvor.dev/contact?intent=trial&product=veyron\n\
         \n\
         Once you receive your key, set it with:\n\
           export VEYRON_LICENSE_KEY=\"<your-key>\"\n\
         or place it in: {}\n\
         \n\
         Contact sales@zyvor.dev for assistance.",
        dirs_key_path().display()
    )
}

fn dirs_key_path() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    PathBuf::from(format!("{}/.config/veyron/license.key", home))
}

fn parse_and_verify(raw: &str) -> Result<License> {
    let parts: Vec<&str> = raw.splitn(2, '.').collect();
    if parts.len() != 2 {
        bail!("Malformed licence key (expected <payload>.<signature>)");
    }
    let payload_b64 = parts[0];
    let sig_b64 = parts[1];

    // Verify HMAC
    let mut mac = HmacSha256::new_from_slice(HMAC_SECRET)
        .map_err(|_| anyhow::anyhow!("HMAC init failed"))?;
    mac.update(payload_b64.as_bytes());
    let sig_bytes = URL_SAFE_NO_PAD
        .decode(sig_b64)
        .map_err(|_| anyhow::anyhow!("Invalid licence key signature encoding"))?;
    mac.verify_slice(&sig_bytes)
        .map_err(|_| anyhow::anyhow!("Licence key signature is invalid — contact sales@zyvor.dev"))?;

    // Decode payload
    let payload_bytes = URL_SAFE_NO_PAD
        .decode(payload_b64)
        .map_err(|_| anyhow::anyhow!("Invalid licence key payload encoding"))?;
    let payload: serde_json::Value = serde_json::from_slice(&payload_bytes)
        .map_err(|_| anyhow::anyhow!("Malformed licence key payload"))?;

    // Validate product
    if payload.get("p").and_then(|v| v.as_str()) != Some("veyron") {
        bail!("This licence key is not valid for Veyron");
    }

    let issued = parse_date(&payload, "iss")?;
    let expires = parse_date(&payload, "exp")?;
    let licensee = payload
        .get("who")
        .and_then(|v| v.as_str())
        .unwrap_or("Unknown")
        .to_string();

    Ok(License { licensee, issued, expires })
}

fn parse_date(payload: &serde_json::Value, key: &str) -> Result<NaiveDate> {
    let s = payload
        .get(key)
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow::anyhow!("Missing '{}' in licence payload", key))?;
    NaiveDate::parse_from_str(s, "%Y-%m-%d")
        .map_err(|_| anyhow::anyhow!("Invalid date '{}' in licence payload", s))
}
